# Predict the number generated by system
import random

num = random.randint(10, 50)
n = int(input("Predict the number between 10 and 50: "))

for i in range(1, 6):
    if num == n:
        print("You got it!!!")
        break
    elif num > n:
        print("Predict a greater value...")
        n = int(input())
    else:
        print("Predict a lesser value...")
        n = int(input())

print("The number is ", num)
